services:
  - type: web
    name: mahalla-yetakchisi-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: python main.py
    pythonVersion: 3.10.11
    envVars:
      - key: BOT_TOKEN
        value: <TOKEN>
      - key: ADMIN_GROUP_ID
        value: "<ADMIN_ID>"
      - key: WEBHOOK_DOMAIN
        value: https://mahalla-bot.onrender.com
      - key: WEBHOOK_PATH
        value: /webhook