services:
  - type: web
    name: mahalla-yetakchisi-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: ADMINS
        sync: false
    region: oregon
    runtime: python
    pythonVersion: 3.10.11