services:
  - type: web
    name: mahalla-yetakchisi-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: python main.py
    pythonVersion: 3.10.11  # ← MUHIM QATOR
    envVars:
      - key: BOT_TOKEN
        value: 8223382586:AAFb7eM0961nxzoH0fOlRNcqacVIVaNurR4
      - key: ADMIN_GROUP_ID
        value: "-1002577499976"
      - key: WEBHOOK_DOMAIN
        value: https://mahalla-bot.onrender.com
      - key: WEBHOOK_PATH
        value: /webhook